//wrench pickup

ServerEvents.tags('block', event => {

    event.add('create:wrench_pickup', 'minecraft:chain')
    event.add('create:wrench_pickup', '#minecraft:candles')
    event.add('create:wrench_pickup', '#supplementaries:candle_holders')
    event.add('create:wrench_pickup', 'minecraft:lightning_rod')
    event.add('create:wrench_pickup', 'farmersdelight:basket')
    event.add('create:wrench_pickup', 'minecraft:barrel')
    event.add('create:wrench_pickup', '#tconstruct:smeltery')
    event.add('create:wrench_pickup', 'tconstruct:seared_table')
    event.add('create:wrench_pickup', 'tconstruct:seared_basin')
    event.add('create:wrench_pickup', 'tconstruct:seared_faucet')
    event.add('create:wrench_pickup', 'tconstruct:seared_channel')
    event.add('create:wrench_pickup', '#tconstruct:foundry')
    event.add('create:wrench_pickup', 'tconstruct:scorched_table')
    event.add('create:wrench_pickup', 'tconstruct:scorched_basin')
    event.add('create:wrench_pickup', 'tconstruct:scorched_faucet')
    event.add('create:wrench_pickup', 'tconstruct:scorched_channel')
    event.add('create:wrench_pickup', 'thermal:machine_frame')
    event.add('create:wrench_pickup', 'quark:crate')
    event.add('create:wrench_pickup', '#botania:special_floating_flowers')
    event.add('create:wrench_pickup', 'botania:apothecary_deepslate')
    event.add('create:wrench_pickup', 'botania:mana_spreader')
    event.add('create:wrench_pickup', 'botania:elven_spreader')
    event.add('create:wrench_pickup', 'botania:gaia_spreader')
    event.add('create:wrench_pickup', 'botania:redstone_spreader')
    event.add('create:wrench_pickup', 'botania:dolluted_pool')
    event.add('create:wrench_pickup', 'botania:mana_pool')
    event.add('create:wrench_pickup', 'botania:fabulous_pool')
    event.add('create:wrench_pickup', 'botania:creative_pool')
    event.add('create:wrench_pickup', 'botania:runic_altar')
    event.add('create:wrench_pickup', 'botania:brewery')
    event.add('create:wrench_pickup', 'botania:mana_pylon')
    event.add('create:wrench_pickup', 'botania:natura_pylon')
    event.add('create:wrench_pickup', 'botania:gaia_pylon')


})