StartupEvents.registry('item', e => {
	e.create('incomplete_redstone_magnet', 'create:sequenced_assembly').texture('create_new_age:item/magnetite_block').displayName('Incomplete Redstone Magnet').modelJson({parent: 'create_new_age:item/magnetite_block'})
	e.create('incomplete_layered_magnet', 'create:sequenced_assembly').texture('create_new_age:item/redstone_magnet').displayName('Incomplete Layered Magnet').modelJson({parent: 'create_new_age:item/redstone_magnet'})
	e.create('incomplete_fluxuated_magnetite', 'create:sequenced_assembly').texture('create_new_age:item/layered_magnet').displayName('Incomplete Fluxuated Magnetite').modelJson({parent: 'create_new_age:item/layered_magnet'})
	e.create('incomplete_netherite_magnet', 'create:sequenced_assembly').texture('create_new_age:item/fluxuated_magnetite').displayName('Incomplete Netherite Magnet').modelJson({parent: 'create_new_age:item/fluxuated_magnetite'})
        e.create('incomplete_connector', 'create:sequenced_assembly').texture('createaddition:item/connector').displayName('Incomplete Small Connector')
        e.create('incomplete_large_connector', 'create:sequenced_assembly').texture('createaddition:item/large_connector').displayName('Incomplete Large Connector')
	e.create('incomplete_slime_gear_1').displayName('Blended Slime Gear').texture('kubejs:item/blendslime_gear')
	e.create('incomplete_molten_gear', 'create:sequenced_assembly').texture('thermal:item/signalum_gear').displayName('Incomplete Molten Gear')
	e.create('incomplete_slime_gear_2', 'create:sequenced_assembly').displayName('Forging Slime Gear').texture('kubejs:item/forgeslime_gear')
	e.create('gold_ring').displayName('Gold Bushing')
	e.create('rubber_gear').displayName('Rubberized Gear')
	e.create('brass_ring').displayName('Brass Bushing')
	e.create('slimesteel_gear').displayName('Slimesteel Gear')
	e.create('cinderslime_gear').displayName('Cinderslime Gear')
	e.create('queenslime_gear').displayName('Queen\'s Slime Gear')
	e.create('forgeslime_gear').displayName('Forged Slime Gear')
	e.create('incomplete_brass_frame', 'create:sequenced_assembly').texture('kubejs:block/brass_frame').displayName('Incomplete Brass Frame').modelJson({parent: 'kubejs:block/brass_frame'})
	e.create('incomplete_end_portal_frame', 'create:sequenced_assembly').displayName('Incomplete Artificial Portal Frame').modelJson({parent: 'kubejs:block/incomplete_end_portal_frame'})
	e.create('coke_dust').displayName('Coke Dust')
	e.create('netherite_rod').displayName('Netherite Rod')
	e.create('incomplete_netherite_frame', 'create:sequenced_assembly').texture('kubejs:block/netherite_frame').displayName('Incomplete Netherite Frame').modelJson({parent: 'kubejs:block/netherite_frame'})
	e.create('incomplete_sturdy_gear', 'create:sequenced_assembly').texture('thermal:item/quartz_gear').displayName('Incomplete Sturdy Gear')
	e.create('incomplete_energized_gear', 'create:sequenced_assembly').texture('thermal:item/ruby_gear').displayName('Incomplete Energized Gear')
	e.create('incomplete_transmitter', 'create:sequenced_assembly').texture('create:item/copper_sheet').displayName('Incomplete Transmitter')
	e.create('rounded_quartz').displayName('Rounded Quartz')
	e.create('placeholder').texture('minecraft:item/barrier').displayName('Placeholder')

})